### ISSUE TITLE
Any referenced papers available?

### ISSUE THREAD

**Issue by LionnelBall** [nyuxz/ds1008_final_project#1]
I have noticed that most of current single image super resolution (SISR) approach used the whole image data as input. So what's the key benefit of this method besides low computational cost? Are there any papers that can be referenced?

**Comment by nyuxz** [comment]
We tested the computational cost in terms of using OOIS data for super-resolution. I don't have a reference list for a similar task, but love to share our project result. We will post our project paper soon.
